version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt
    username: x-access-token
    password: ${{ secrets.READER_TOKEN }}

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      minor-deps:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: maven
    directory: "/"
    registries:
      - maven-github
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    allow:
      - dependency-type: "all"
    groups:
      prod-deps:
        dependency-type: "production"
        exclude-patterns:
          - "no.nav.*"
        update-types:
          - "minor"
          - "patch"
      dev-deps:
        dependency-type: "development"
        exclude-patterns:
          - "no.nav.*"
        update-types:
          - "minor"
          - "patch"
      interne-deps:
        patterns:
          - "no.nav.*"
        update-types:
          - "minor"
          - "patch"

