version: '3.7'
services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0-slim-faststart
    container_name: oracle_new
    environment:
      TZ: Europe/Oslo
      ORACLE_PASSWORD: oracle
    shm_size: 4gb
    ports:
      - "127.0.0.1:1521:1521"
    volumes:
      - ./oracle-init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
