version: '2.4'
services:
  audit.nais:
    image: $AUDIT_NAIS_IMAGE
    container_name: audit.nais
    ports:
      - "6514:6514"
    mem_limit: 32m
  oracle:
    image: $ORACLE_IMAGE
    container_name: oracle
    restart: on-failure
    mem_limit: 1gb
    mem_reservation: 512mb
    shm_size: 2gb
    volumes:
      - ./oracle-init:/docker-entrypoint-initdb.d/
    ports:
      - "1521:1521"
  postgres:
    image: $POSTGRES_IMAGE
    container_name: postgres
    restart: on-failure
    mem_limit: 128mb
    environment:
      - "TZ=Europe/Oslo"
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  vtp:
    image: $VTP_IMAGE
    container_name: vtp
    restart: on-failure
    mem_limit: 2gb
    mem_reservation: 1gb
    environment:
      - "NO_NAV_MODIG_SECURITY_APPCERT_KEYSTORE=/var/run/secrets/naisd.io/keystore.jks"
      - "JAVAX_NET_SSL_TRUSTSTORE=/var/run/secrets/naisd.io/truststore.jks"
      - "CREATE_TOPICS=privat-foreldrepenger-fprisk-lokal,privat-foreldrepenger-kontroll-resultat-lokal,privat-familie-vedtakFattet-v1-vtp,aapen-sob-oppgaveHendelse-v1,tilbakebetaling-aksjonspunkthendelse"
    volumes:
      - "~/.modig:/var/run/secrets/naisd.io"
    ports:
      - "8060:8060"
      - "8063:8063"
      - "8636:8636"
      - "9093:9093"
      - "9092:9092"
      - "8389:8389"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8060/rest/isReady"]
      interval: 15s
      timeout: 5s
      retries: 5
  fpabakus:
    image: $FPABAKUS_IMAGE
    container_name: fpabakus
    restart: on-failure
    mem_limit: 512mb
    environment:
      - "TZ=Europe/Oslo"
      - "NAIS_CLUSTER_NAME=LOCALHOST-FSS" #omgår avhengighet til vault
      - "LOADBALANCER_URL=http://localhost:8015"
      - "LOADBALANCER_FQDN=localhost:8015"
    env_file:
      - "fpabakus_datasource.list"
      - "common.env"
    volumes:
      - "~/.modig:/var/run/secrets/naisd.io"
    ports:
      - "8015:8080"
    depends_on:
      audit.nais:
        condition: service_started
      postgres:
        condition: service_started
      vtp:
        condition: service_healthy
  fpsak:
    image: $FPSAK_IMAGE
    container_name: fpsak
    restart: on-failure
    mem_limit: 1gb
    environment:
      - "PIP_USERS=im-just-a-fake-code,srvfpoppdrag,srvfplos,srvfptilbake,srvfpformidling"
      - "FPABAKUS_URL=http://fpabakus:8080/fpabakus"
      - "FPOPPDRAG_OVERRIDE_PROXY_URL=http://localhost:9000/fpoppdrag/api"
      - "FPOPPDRAG_OVERRIDE_DIREKTE_URL=http://fpoppdrag:8080/fpoppdrag/api"
      - "FPTILBAKE_OVERRIDE_DIREKTE_URL=http://fptilbake:8080/fptilbake/api"
      - "FPRISK_RISIKOKLASSIFISERING_HENT_URL=http://fprisk:8080/fprisk/api/risikovurdering/hent"
      - "KAFKA_SAKOGBEHANDLING_TOPIC=aapen-sob-oppgaveHendelse-v1"
      - "LOADBALANCER_URL=http://localhost:8080"
      - "LOADBALANCER_FQDN=localhost:8080"
      - "EXTRA_CLASS_PATH=:vtp-lib/*"
    env_file:
      - "fpsak_datasource.list"
      - "common.env"
    volumes:
      - "~/.modig:/var/run/secrets/naisd.io"
    ports:
      - "8080:8080"
    depends_on:
      - audit.nais
      - oracle
      - vtp
      - fpabakus
  fpformidling:
    image: $FPFORMIDLING_IMAGE
    container_name: fpformidling
    restart: on-failure
    mem_limit: 512mb
    environment:
      - "TZ=Europe/Oslo"
      - "FPSAK_REST_BASE_URL=http://fpsak:8080"
      - "NAIS_CLUSTER_NAME=LOCALHOST-FSS" #omgår avhengighet til vault
      - "LOADBALANCER_URL=http://localhost:8010"
      - "LOADBALANCER_FQDN=localhost:8010"
    env_file:
      - "fpformidling_datasource.list"
      - "common.env"
    volumes:
      - "~/.modig:/var/run/secrets/naisd.io"
    ports:
      - "8010:8080"
    depends_on:
      - postgres
      - vtp
      - fpsak
  fpoppdrag:
    image: $FPOPPDRAG_IMAGE
    container_name: fpoppdrag
    restart: on-failure
    mem_limit: 512mb
    env_file:
      - "fpoppdrag_datasource.list"
      - "common.env"
    environment:
      - "OPPDRAG_SERVICE_URL=https://vtp:8063/soap/cics/services/oppdragService"
      - "LOADBALANCER_URL=http://localhost:8070"
      - "LOADBALANCER_FQDN=localhost:8070"
      - "OPENIDCONNECT_USERNAME=fpoppdrag-localhost"
    volumes:
      - "~/.modig:/var/run/secrets/naisd.io"
    ports:
      - "8070:8080"
    depends_on:
      - oracle
      - vtp
      - fpsak
  fptilbake:
    image: $FPTILBAKE_IMAGE
    container_name: fptilbake
    restart: on-failure
    mem_limit: 512mb
    env_file:
      - "fptilbake_datasource.list"
      - "common.env"
    environment:
      - "FPSAK_OVERRIDE_URL=http://fpsak:8080"
      - "FPOPPDRAG_OVERRIDE_URL=http://fpoppdrag:8080"
      - "FPSAK_PIP_AKTOER_FOR_SAK_URL=https://fpsak:8080/fpsak/api/pip/aktoer-for-sak"
      - "JOURNALPOSTAPI_OVERRIDE_URL=https://vtp:8063/rest/dokarkiv/"
      - "TILBAKEKREVING_V1_URL=https://vtp:8063/soap/tilbakekreving/services/tilbakekrevingService"
      - "KAFKA_FPLOS_TOPIC=tilbakebetaling-aksjonspunkthendelse"
      - "KAFKA_FPLOS_CLIENT_ID=tilbakebetaling-aksjonspunkthendelse"
      - "LOADBALANCER_URL=http://localhost:8030"
      - "LOADBALANCER_FQDN=localhost:8030"
      - "EXTRA_CLASS_PATH=:vtp-lib/*"
      - "TEST_ONLY_DISABLE_MQ=true"
      - "ABAC_ATTRIBUTT_APPLIKASJON=no.nav.abac.attributter.foreldrepenger"
      - "ABAC_ATTRIBUTT_FAGSAK=no.nav.abac.attributter.foreldrepenger.fagsak"
      - "ABAC_ATTRIBUTT_VENTEFRIST=no.nav.abac.attributter.foreldrepenger.fagsak.ventefrist"
      - "ABAC_ATTRIBUTT_BATCH=no.nav.abac.attributter.foreldrepenger.batch"
    volumes:
      - "~/.modig:/var/run/secrets/naisd.io"
    ports:
      - "8030:8080"
    depends_on:
      - oracle
      - vtp
      - fpsak
  fprisk:
    image: $FPRISK_IMAGE
    container_name: fprisk
    restart: on-failure
    mem_limit: 512mb
    env_file:
      - "fprisk_datasource.list"
      - "common.env"
    environment:
      - "LOADBALANCER_URL=http://localhost:8075"
      - "OPENIDCONNECT_USERNAME=fprisk-localhost"
      - "BRREG_PROXY=https://vtp:8063/rest/brreg/proxy/not/implemented"
    volumes:
      - "~/.modig:/var/run/secrets/naisd.io"
    ports:
      - "8075:8080"
    depends_on:
      - oracle
      - vtp
      - fpsak
  redis:
    image: redis
    container_name: redis
    restart: on-failure
    mem_limit: 64mb
  fpfrontend:
    image: $FPFRONTEND_IMAGE
    container_name: fpfrontend
    restart: on-failure
    mem_limit: 64mb
    environment:
      - "TZ=Europe/Oslo"
      - "APP_PORT=9000"
      - "APP_URL_FPSAK=http://fpsak:8080"
      - "APP_URL_FPOPPDRAG=http://fpoppdrag:8080"
      - "APP_URL_FPFORMIDLING=http://fpformidling:8080"
      - "OIDC_HOST_URL=https://vtp:8063/rest/isso/oauth2"
      - "OIDC_AGENTNAME=fpsak-localhost"
      - "OIDC_PASSWORD=vtp"
      - "REDIS_HOST=redis"
    volumes:
      - "./frontend/:/nginx"
    ports:
      - "9000:9000"
    depends_on:
      - fpsak
      - redis
