-- ###############################
-- ### Opplegg for lokal jetty ###
-- ###############################
DECLARE userexists INTEGER;
BEGIN
  SELECT count(*)
  INTO userexists
  FROM SYS.ALL_USERS
  WHERE USERNAME = 'FPINFO_SCHEMA';
  IF (userexists = 0)
  THEN
    EXECUTE IMMEDIATE ('CREATE USER FPINFO_SCHEMA IDENTIFIED BY fpinfo_schema');
  END IF;
END;
/

DECLARE userexists INTEGER;
BEGIN
  SELECT count(*)
  INTO userexists
  FROM SYS.ALL_USERS
  WHERE USERNAME = 'FPINFO';
  IF (userexists = 0)
  THEN
    EXECUTE IMMEDIATE ('CREATE USER FPINFO IDENTIFIED BY fpinfo');
  END IF;
END;
/

GRANT CONNECT, RESOURCE, CREATE JOB, CREATE TABLE, CREATE SYNONYM, CREATE VIEW, CREATE MATERIALIZED VIEW TO FPINFO_SCHEMA;
GRANT CONNECT, RESOURCE, CREATE JOB, CREATE TABLE, CREATE SYNONYM, CREATE VIEW, CREATE MATERIALIZED VIEW TO FPINFO;


BEGIN
    EXECUTE IMMEDIATE ('GRANT CREATE VIEW TO FPINFO_SCHEMA WITH ADMIN OPTION');
    EXECUTE IMMEDIATE ('GRANT CONNECT TO fpsak');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.FAGSAK                      TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.KODELISTE                   TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.FH_FAMILIE_HENDELSE         TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.GR_PERSONOPPLYSNING         TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.PO_INFORMASJON              TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.PO_RELASJON                 TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.SO_ANNEN_PART               TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.GR_FAMILIE_HENDELSE         TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.BRUKER                      TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.BEHANDLING                  TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.MOTTATT_DOKUMENT            TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.AKSJONSPUNKT                TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.BEHANDLING_RESULTAT         TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.BEHANDLING_ARSAK            TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.BEHANDLING_VEDTAK           TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.UTTAK_RESULTAT_PERIODE      TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.UTTAK_RESULTAT_PERIODE_AKT  TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.UTTAK_RESULTAT              TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.UTTAK_RESULTAT_PERIODER     TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.FAGSAK_RELASJON             TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.FH_ADOPSJON                 TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.FH_TERMINBEKREFTELSE        TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.FH_UIDENTIFISERT_BARN       TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.SO_SOEKNAD                  TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.SO_DEKNINGSGRAD             TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.SO_RETTIGHET                TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.YF_DOKUMENTASJON_PERIODE    TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.YF_FORDELING_PERIODE        TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.GR_YTELSES_FORDELING        TO  fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.UTTAK_RESULTAT_PERIODE_SOKNAD        TO fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.UTTAK_AKTIVITET             TO fpinfo_schema WITH GRANT OPTION');
    EXECUTE IMMEDIATE ('GRANT SELECT ON fpsak.YF_FORDELING                TO fpinfo_schema WITH GRANT OPTION');
END;
/
