name: Utfører tester mot SUT

on:
  workflow_call:
    inputs:
      build-version:
        required: false
        type: string
        description: 'Docker tag (from repository)'
        default: 'latest'
      test-suites:
        description: 'Test suite å kjøre (fpsak|fptilbake|verdikjede)'
        type: string
        required: true
    outputs:
      fpsak:
        description: "Fpsak resultat tester"
        value: ${{ jobs.fpsak.outputs.result }}
      fptilbake:
        description: "Fptilbake resultat tester"
        value: ${{ jobs.fptilbake.outputs.result }}
      verdikjede:
        description: "Verdikjedetester resultat"
        value: ${{ jobs.verdikjede.outputs.result }}

jobs:
  fpsak:
    name: Kjører tester fra test suite fpsak mot ${{ github.repository }} ${{ inputs.build-version }}
    if: contains(inputs.test-suites, 'fpsak')
    runs-on: ubuntu-latest-8-cores
    timeout-minutes: 15
    outputs:
      result: ${{ steps.result.outputs.result }}
    steps:
      - uses: ./.github/actions/setup-and-test
        with:
          build-version: ${{ needs.build-app.outputs.build-version }}
          test-suite: fpsak
          parallellitet: 16

  fptilbake:
    name: Kjører tester fra test suite fptilbake mot ${{ github.repository }} ${{ inputs.build-version }}
    if: contains(inputs.test-suites, 'fptilbake')
    runs-on: ubuntu-latest-8-cores
    timeout-minutes: 15
    outputs:
      result: ${{ steps.result.outputs.result }}
    steps:
      - uses: ./.github/actions/setup-and-test
        with:
          build-version: ${{ needs.build-app.outputs.build-version }}
          test-suite: fptilbake
          parallellitet: 8

  verdikjede:
    name: Kjører tester fra test suite verdikjede mot ${{ github.repository }} ${{ inputs.build-version }}
    if: contains(inputs.test-suites, 'verdikjede')
    runs-on: ubuntu-latest-8-cores
    timeout-minutes: 15
    outputs:
      result: ${{ steps.result.outputs.result }}
    steps:
      - uses: ./.github/actions/setup-and-test
        with:
          build-version: ${{ needs.build-app.outputs.build-version }}
          test-suite: verdikjede
          parallellitet: 8
