name: Kjører Autotestene ved bygg

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - '.editorconfig'
      - '.java-version'
      - '.gitattributes'
      - 'LICENSE'
      - 'CODEOWNERS'
      - '.github/workflows/trigger.yml.yml'
      - 'docs/**'
      - '.github/*.yml'

jobs:
  fpsak-tester:
    name: Fpsak tester
    if: github.ref_name != 'master'
    uses: navikt/fp-autotest/.github/workflows/autotest.yml@master
    with:
      test-suite: fpsak
    secrets: inherit

  fptilbake-tester:
    name: Fptilbake tester
    if: github.ref_name == 'master'
    uses: navikt/fp-autotest/.github/workflows/autotest.yml@master
    with:
      test-suite: fptilbake
    secrets: inherit

  verdikjede-tester:
    name: Verdikjedetester
    if: github.ref_name == 'master'
    uses: navikt/fp-autotest/.github/workflows/autotest.yml@master
    with:
      test-suite: verdikjede
    secrets: inherit
