name: Kjører Autotestene for verdikjeden PR

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'CODEOWNERS'
      - '.github/workflows/trigger.yml.yml'
      - 'lokalutvikling/*'

jobs:
  fpsak:
    name: Kjører tester fra test suite fpsak mot ${{ github.repository }} ${{ inputs.build-version }}
    uses: navikt/fp-autotest/.github/workflows/autotest.yml@test
    with:
      build-version: ${{ needs.build-app.outputs.build-version }}
      test-suites: fpsak
      parallellitet: 16
    secrets: inherit
