name: Kjører Autotestene for fp-sak

on:
  push:
    branches:
      - master         # Push events on master branch
  repository_dispatch:
    types: [fpsak-autotest]

jobs:
  build:
    name: Utfør verdikjede-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Hent maven version
        run: |
          echo "::set-env name=CACHE_KEY::$(date +%U)"
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ env.CACHE_KEY }}

      - name: Setup fp-sak stack
        shell: bash
        run: |
          echo ::set-env name=STACK_STARTED::false
          echo "Oppretter dummy keystore for testing"
          cd resources/keystore
          ./make-dummy-keystore.sh
          echo "${{ secrets.GITHUB_ACCESS_TOKEN }}" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          cd ../pipeline
          ./update-versions.sh ${{ github.event.client_payload.trigger }} ${{ github.event.client_payload.version }}
          docker-compose up --quiet-pull --detach

      - name: Venter på stacken og sjekker status
        shell: bash
        run: |
          echo ::set-env name=STACK_CREATED::true
          docker ps -a
          echo
          echo "Tester om VTP er oppe"
          timeout 5 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8060/rest/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo
          echo "Tester om abakus er oppe"
          timeout 60 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8015/fpabakus/internal/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo
          echo "Tester om fp-formidling er oppe"
          echo "Sjekker ikke fp-formidling fordi curl mot isReady returnerte 400 bad request. Antar at den er oppe!"
          echo
          echo "Tester om fp-sak er oppe"
          timeout 120 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/fpsak/internal/health/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo ::set-env name=STACK_STARTED::true

      - name: Utfører tester
        shell: bash
        run: |
          mvn test --batch-mode --settings .m2/settings.xml -P fpsak -DargLine="AUTOTEST_ENV=pipeline"
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Trigger deploy av fpsak til T4
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          repository: navikt/fp-sak
          event-type: update-issue-fpsak
          client-payload: '{ "issue-number": "${{ github.event.client_payload.issue-number }}", "success": "true"}'

      - name: Trigger ikke deploy av fpsak til T4
        if: failure() && ${{ github.event.event_type }} == "fpsak-autotest" && ${{ github.event.client_payload.issue-number }} != null
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          repository: navikt/fp-sak
          event-type: update-issue-fpsak
          client-payload: '{ "issue-number": "${{ github.event.client_payload.issue-number }}", "success": "false"}'

      - name: Generer testrapport
        if: always() && env.STACK_STARTED == 'true'
        shell: bash
        run: |
          cd resources/allure
          ./set-environment-variables.sh ${{ github.event.client_payload.trigger }}
          cd ../../target/allure-results
          git fetch origin gh-pages
          git checkout origin/gh-pages ../../history
          cp -r ../../history history
          cp ../../resources/allure/environment.properties .
          cp ../../resources/allure/categories.json .
          cd ../..
          mvn allure:report --batch-mode --file pom.xml

      - name: Dumper logger for feilsøking
        if: failure() && env.STACK_CREATED == 'true'
        run: |
          mkdir container-logs
          cd container-logs
          docker logs fpsak --tail all > fp-sak.log
          docker logs abakus --tail all > abakus.log
          docker logs fpformidling --tail all > fp-formidling.log
          docker logs vtp --tail all > vtp.log
          docker logs oracle --tail all > oracle.log
          docker logs postgres --tail all > postgres.log

      - name: Laste opp logger
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: container-logs

      - name: Deploy testrapport
        if: always() && env.STACK_STARTED == 'true'
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          target_branch: gh-pages
          build_dir: target/allure-report/
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Notification til slack
        if: failure() || env.STACK_STARTED == 'false'
        shell: bash
        run: |
          curl -X POST --data-urlencode \
          'payload={"channel": "#fpsak-autotest",
          "username": "autotestern",
          "blocks": [ { "type": "section", "text": {
          "type": "mrkdwn",
          "text": "  :scream: De automatiske testene feilet: <https://navikt.github.io/fpsak-autotest/|Testrapport> \n
          repository: ${{ github.event.client_payload.trigger }} versjon: ${{ github.event.client_payload.version }} "
          } } ],
          "icon_emoji": ":snowman:"}' ${{ secrets.SLACK_WEBHOOK }}

