name: Kjører Autotestene for verdikjeden PR

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'CODEOWNERS'
      - '.github/workflows/trigger.yml.yml'
      - 'lokalutvikling/*'

jobs:
  autotest:
    name: Autotest
    uses: navikt/fp-autotest/.github/workflows/autotest-resuable.yml@test
    with:
      build-version: ${{ needs.build-app.outputs.build-version }}
      test-suites: fpsak, fptilbake
    secrets: inherit


#  autotest-matrix:
#    name: Autotest
#    strategy:
#      matrix:
#        test-suite: [ fpsak, fptilbake ]
#    uses: navikt/fp-autotest/.github/workflows/autotest-resuable.yml@test
#    with:
#      build-version: ${{ needs.build-app.outputs.build-version }}
#      test-suites: ${{ matrix.test-suite }}
#    secrets: inherit




#
#  autotest-composite:
#    name: Autotest-comp
#    uses: navikt/fp-autotest/.github/workflows/autotest-composite.yml@test
#    with:
#      build-version: ${{ needs.build-app.outputs.build-version }}
#      test-suites: fpsak
#    secrets: inherit
