name: "Pull Request Labeler"
on:
  pull_request_target:
jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/labeler@17086b774338d2689ada0d8fcc8c51b5c9bc782a # ratchet:actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
