name: notify-slack
on:
  repository_dispatch:
    types: [notify-slack]


env:
  TRIGGER:  ${{ github.event.client_payload.trigger }}
  VERSION: ${{ github.event.client_payload.version }}
  STACK_STARTED:  ${{ github.event.client_payload.stack_started }}
  TEST_OUTCOME:  ${{ github.event.client_payload.test_outcome }}
  TEST_RESULTAT: ${{ github.event.client_payload.test_resultat }}
  TEST_SUITE: ${{ github.event.client_payload.test_suite }}
  RUN_ID: ${{ github.event.client_payload.run_id }}

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:

      - name: Henter ut historie
        id: slacknotify
        uses: actions/checkout@v2.3.4
        with:
          repository: ${{ env.TRIGGER }}
          path: ${{ env.TRIGGER }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          fetch-depth: 5

      - name: Hent ut versjon fra forrige issue
        if: always() && steps.slacknotify.outcome == 'success'
        shell: bash
        run: |
          CURRENT_HASH=$(echo "${{ env.VERSION }}" | awk -F'-' '{print $3}')
          cd "${{ env.TRIGGER }}"
          git remote -v
          git fetch
          echo "DIFFERANSE=$(git log --pretty=format:"%s; author: %an" -n 1 ${CURRENT_HASH})" >> $GITHUB_ENV

      - name: Bygger opp slack melding
        if: always()
        shell: bash
        run: |
          if [ ${{ env.STACK_STARTED }} == true ]; then
            echo "Stack up and running!"
            if [ ${{ env.TEST_SUITE }} != verdikjede ]; then
              echo 'SLACK_MESSAGE<<\n' >> $GITHUB_ENV
                echo '*Trigger*: ${{ env.TRIGGER }}:${{ env.VERSION }}' >> $GITHUB_ENV
                echo '*Resultat*: ${{ env.TEST_RESULTAT }}, Rapport: <https://navikt.github.io/fpsak-autotest/fpsak|Allure rapport>' >> $GITHUB_ENV
                echo '*Endringer*: ${{ env.DIFFERANSE }}' >> $GITHUB_ENV
                echo '*Action URL*: <https://github.com/navikt/fpsak-autotest/actions/runs/${{ env.RUN_ID }}|Github Action Url>' >> $GITHUB_ENV
              echo '\n' >> $GITHUB_ENV
              if [ ${{ env.TEST_OUTCOME }} == success ]; then
                echo "Test success!"
                echo "SLACK_TITLE=Autotestene er kjørt UTEN feil :rocket:" >> $GITHUB_ENV
                echo "SLACK_COLOR=#37df1d" >> $GITHUB_ENV
              else
                echo "Test failure!"
                echo "SLACK_TITLE=Autotestene feilet :boom:" >> $GITHUB_ENV
                echo "SLACK_COLOR=#df1515" >> $GITHUB_ENV
              fi
            else
              echo 'SLACK_MESSAGE<<\n' >> $GITHUB_ENV
                echo '*Trigger*: ${{ env.TRIGGER }}:${{ env.VERSION }}' >> $GITHUB_ENV
                echo '*Resultat*: ${{ env.TEST_RESULTAT }}, Rapport: <https://navikt.github.io/fpsak-autotest/verdikjede|Allure rapport>' >> $GITHUB_ENV
                echo '*Endringer*: ${{ env.DIFFERANSE }}' >> $GITHUB_ENV
                echo '*Action URL*: <https://github.com/navikt/fpsak-autotest/actions/runs/${{ env.RUN_ID }}|Github Action Url>' >> $GITHUB_ENV
              echo '\n' >> $GITHUB_ENV
              if [ ${{ env.TEST_OUTCOME }} == success ]; then
                echo "Test success!"
                echo "SLACK_TITLE=Verdikjedetestene er kjørt UTEN feil :rocket:" >> $GITHUB_ENV
                echo "SLACK_COLOR=#37df1d" >> $GITHUB_ENV
              else
                echo "Test failure!"
                echo "SLACK_TITLE=Verdikjedetestene feilet :boom:" >> $GITHUB_ENV
                echo "SLACK_COLOR=#df1515" >> $GITHUB_ENV
              fi
            fi
          else
            echo "Noe gikk galt. GHA fikk ikke opp verdikjeden"
            echo "SLACK_TITLE=Noe gikk galt. GHA fikk ikke opp verdikjeden :man-shrugging:" >> $GITHUB_ENV
            echo 'SLACK_MESSAGE<<\n' >> $GITHUB_ENV
              echo '*Trigger*: ${{ env.TRIGGER }}:${{ env.VERSION }}' >> $GITHUB_ENV
              echo '*Endringer*: ${{ env.DIFFERANSE }}' >> $GITHUB_ENV
              echo '*Action URL*: <https://github.com/navikt/fpsak-autotest/actions/runs/${{ env.RUN_ID }}|Github Action Url>' >> $GITHUB_ENV
            echo '\n' >> $GITHUB_ENV
            echo "SLACK_COLOR=#e79a07" >> $GITHUB_ENV
          fi

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2.1.1
        env:
          SLACK_CHANNEL: vtp-autotest-resultat
          SLACK_COLOR: ${{ env.SLACK_COLOR }}
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: ${{ env.SLACK_TITLE }}
          SLACK_MESSAGE: ${{ env.SLACK_MESSAGE }}
          SLACK_USERNAME: Github Action
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: ''
          MSG_MINIMAL: true

