name: notify-slack
on:
  repository_dispatch:
    types: [notify-slack]


env:
  TRIGGER:  ${{ github.event.client_payload.trigger }}
  VERSION: ${{ github.event.client_payload.version }}
  STACK_STARTED:  ${{ github.event.client_payload.stack_started }}
  TEST_OUTCOME:  ${{ github.event.client_payload.test_outcome }}
  LOGGTEST_OUTCOME:  ${{ github.event.client_payload.loggtest_outcome }}
  TEST_RESULTAT: ${{ github.event.client_payload.test_resultat }}
  TEST_SUITE: ${{ github.event.client_payload.test_suite }}
  RUN_ID: ${{ github.event.client_payload.run_id }}

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:

      - name: Henter ut historie
        id: slacknotify
        uses: actions/checkout@v2.3.4
        with:
          repository: ${{ env.TRIGGER }}
          path: ${{ env.TRIGGER }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          fetch-depth: 5

      - name: Hent ut versjon fra forrige issue
        if: always() && steps.slacknotify.outcome == 'success'
        shell: bash
        run: |
          CURRENT_HASH=$(echo "${{ env.VERSION }}" | awk -F'-' '{print $3}')
          cd "${{ env.TRIGGER }}"
          git remote -v
          git fetch
          echo "DIFFERANSE=$(git log --pretty=format:"%s; author: %an" -n 1 ${CURRENT_HASH})" >> $GITHUB_ENV

      - name: Bygger opp slack melding når GHA ikke får opp verdikjeden
        if: always() && env.STACK_STARTED == 'false'
        shell: bash
        run: |
          echo "SLACK_TITLE=Noe gikk galt. GHA fikk ikke opp verdikjeden :man-shrugging:" >> $GITHUB_ENV
          echo 'SLACK_MESSAGE<<\n' >> $GITHUB_ENV
            echo '*Trigger*: ${{ env.TRIGGER }}:${{ env.VERSION }}' >> $GITHUB_ENV
            echo '*Endringer*: ${{ env.DIFFERANSE }}' >> $GITHUB_ENV
            echo '*Action URL*: <https://github.com/navikt/fpsak-autotest/actions/runs/${{ env.RUN_ID }}|Github Action Url>' >> $GITHUB_ENV
            echo '\n' >> $GITHUB_ENV
          echo "SLACK_COLOR=#ff8000" >> $GITHUB_ENV


      - name: Bygger opp slack melding ved testing av fpsak
        if: |
          always() &&
          env.STACK_STARTED == 'true' &&
          env.TEST_SUITE == 'fpsak'
        shell: bash
        run: |
          if [ ${{ env.LOGGTEST_OUTCOME }} != success ] && [ ${{ env.TEST_OUTCOME }} == success ]; then
            echo "SLACK_TITLE=Autotestene gikk grønne, men fant feil i loggen" >> $GITHUB_ENV
            echo 'SLACK_MESSAGE<<\n' >> $GITHUB_ENV
              echo '*Trigger*: ${{ env.TRIGGER }}:${{ env.VERSION }}' >> $GITHUB_ENV
              echo '*Resultat*: Sjekk <https://navikt.github.io/fpsak-autotest/fpsak|testrapport> for feilen(e) i loggen' >> $GITHUB_ENV
              echo '*Endringer*: ${{ env.DIFFERANSE }}' >> $GITHUB_ENV
              echo '*Action URL*: <https://github.com/navikt/fpsak-autotest/actions/runs/${{ env.RUN_ID }}|Github Action Url>' >> $GITHUB_ENV
            echo '\n' >> $GITHUB_ENV
            echo "SLACK_COLOR=#ffff00" >> $GITHUB_ENV
          else
            echo 'SLACK_MESSAGE<<\n' >> $GITHUB_ENV
              echo '*Trigger*: ${{ env.TRIGGER }}:${{ env.VERSION }}' >> $GITHUB_ENV
              echo '*Resultat*: ${{ env.TEST_RESULTAT }}, Rapport: <https://navikt.github.io/fpsak-autotest/fpsak|testrapport>' >> $GITHUB_ENV
              echo '*Endringer*: ${{ env.DIFFERANSE }}' >> $GITHUB_ENV
              echo '*Action URL*: <https://github.com/navikt/fpsak-autotest/actions/runs/${{ env.RUN_ID }}|Github Action Url>' >> $GITHUB_ENV
            echo '\n' >> $GITHUB_ENV
            if [ ${{ env.TEST_OUTCOME }} == success ]; then
              echo "Test success!"
              echo "SLACK_TITLE=Autotestene er kjørt UTEN feil :rocket:" >> $GITHUB_ENV
              echo "SLACK_COLOR=#25d525" >> $GITHUB_ENV
            else
              echo "Test failure!"
              echo "SLACK_TITLE=Autotestene feilet :boom:" >> $GITHUB_ENV
              echo "SLACK_COLOR=#ff0000" >> $GITHUB_ENV
            fi
          fi


      - name: Bygger opp slack melding ved testing av verdikjeden
        if: |
          always() &&
          env.STACK_STARTED == 'true' &&
          env.TEST_SUITE == 'verdikjede'
        shell: bash
        run: |
          if [ ${{ env.LOGGTEST_OUTCOME }} != success ] && [ ${{ env.TEST_OUTCOME }} == success ]; then
            echo "SLACK_TITLE=Verdikjedetestene gikk grønne, men fant feil i loggen" >> $GITHUB_ENV
            echo 'SLACK_MESSAGE<<\n' >> $GITHUB_ENV
              echo '*Trigger*: ${{ env.TRIGGER }}:${{ env.VERSION }}' >> $GITHUB_ENV
              echo '*Resultat*: Sjekk <https://navikt.github.io/fpsak-autotest/verdikjede|testrapport> for feilen(e) i loggen' >> $GITHUB_ENV
              echo '*Endringer*: ${{ env.DIFFERANSE }}' >> $GITHUB_ENV
              echo '*Action URL*: <https://github.com/navikt/fpsak-autotest/actions/runs/${{ env.RUN_ID }}|Github Action Url>' >> $GITHUB_ENV
            echo '\n' >> $GITHUB_ENV
            echo "SLACK_COLOR=#ffff00" >> $GITHUB_ENV
          else
            echo 'SLACK_MESSAGE<<\n' >> $GITHUB_ENV
              echo '*Trigger*: ${{ env.TRIGGER }}:${{ env.VERSION }}' >> $GITHUB_ENV
              echo '*Resultat*: ${{ env.TEST_RESULTAT }}, Rapport: <https://navikt.github.io/fpsak-autotest/verdikjede|Allure rapport>' >> $GITHUB_ENV
              echo '*Endringer*: ${{ env.DIFFERANSE }}' >> $GITHUB_ENV
              echo '*Action URL*: <https://github.com/navikt/fpsak-autotest/actions/runs/${{ env.RUN_ID }}|Github Action Url>' >> $GITHUB_ENV
            echo '\n' >> $GITHUB_ENV
            if [ ${{ env.TEST_OUTCOME }} == success ]; then
              echo "Test success!"
              echo "SLACK_TITLE=Verdikjedetestene er kjørt UTEN feil :rocket:" >> $GITHUB_ENV
              echo "SLACK_COLOR=#25d525" >> $GITHUB_ENV
            else
              echo "Test failure!"
              echo "SLACK_TITLE=Verdikjedetestene feilet :boom:" >> $GITHUB_ENV
              echo "SLACK_COLOR=#ff0000" >> $GITHUB_ENV
            fi
          fi

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2.1.3
        env:
          SLACK_CHANNEL: vtp-autotest-resultat
          SLACK_COLOR: ${{ env.SLACK_COLOR }}
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: ${{ env.SLACK_TITLE }}
          SLACK_MESSAGE: ${{ env.SLACK_MESSAGE }}
          SLACK_USERNAME: Github Action
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: ''
          MSG_MINIMAL: true

