name: Promote
on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Sett variabler for cluster og tag
        run: |
          echo "CLUSTER=$(echo '${{github.event.comment.body}}' | cut -d' ' -f2)" >> $GITHUB_ENV

      - name: Print
        run: |
          echo "Elements in array: ${{ toJSON(github.event.issue.labels) }}"
          echo "Elements in array: ${{ toJSON(github.event.issue.labels.*.name) }}"

      - name: Vent på velykket deploy til dev
        if: env.CLUSTER == 'prod-fss'
        run: |
          echo "Elements in array: ${{ github.event.issue.labels.*.name }}"
          echo "Elements in array: ${{ contains(github.event.issue.labels.*.name, 'bug') }}"
          timeout 180 bash -c \
            'while [ "${{ !contains(github.event.issue.labels.*.name, 'bugger') }}" ]; do
              echo "Labels: ${{ toJSON(github.event.issue.labels.*.name) }}"
              echo "Inneholder label: ${{ !contains(github.event.issue.labels.*.name, 'bugger') }}"
              echo "Inneholder label: ${{ contains(github.event.issue.labels.*.name, 'bugger') }}"
              sleep 2
            done' || false

      - name: Vent på velykket deploy til dev
        run: |
          echo "DEPLOY"

