name: Oppdaterer deployment issue

on:
  repository_dispatch:
    types: [update-issue]

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Test success
        if: github.event.client_payload.success == 'success' && github.event.client_payload.issue-number != null
        id: success
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.trigger }}
          issue-number: ${{ github.event.client_payload.issue-number }}
          body: |
            Alle testene gikk grønne!
            Deployer ${{ github.event.client_payload.trigger }} til q1

      - name: Trigger deploy til teamforeldrepenger
        if: steps.success.outcome == 'success' && github.event.client_payload.trigger != 'navikt/fp-abakus' && github.event.client_payload.trigger != 'navikt/fptilbake'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.trigger }}
          issue-number: ${{ github.event.client_payload.issue-number }}
          body: /promote dev-fss teamforeldrepenger

      - name: Test failure
        if: steps.success.outcome != 'success'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.trigger }}
          issue-number: ${{ github.event.client_payload.issue-number }}
          body: |
            Integrasjonstestene kjørt av fpsak-autotest feilet!

            Det er 4 kjente grunner til at testene feiler:
            1) Det er en feil i ${{ github.event.client_payload.trigger }} som denne mergen har foresaket.
            2) Det er feil i en annen applikasjon i verdikjeden. Autotest bruker siste versjon av alle applikasjonene utenom den som trigger testene.
            3) Det er en feil i testene som må fikses.
            4) Det er en midlertidig feil med Github Action. Ofte kan dette løses med en rekjøring av testene.

            Ønsker du å sjekke loggene eller rekjøre testene kan du gå her: [GA-verdikjedetesten-log][1]
            * For å rekjøre testene trykke du på linken over og inne på denne trykker du på "Re-run jobs" oppe i høyre hjørne.
            * Ønsker du å se loggene for alle applikasjonene kan gå inn samme plass og laste ned artifaktet med navnet "logs".

            På grunn av testfeil deployes IKKE ${{ github.event.client_payload.trigger }} automatisk til q1!

            [1]: https://github.com/navikt/fpsak-autotest/actions/runs/${{ github.event.client_payload.run_id }}
