name: Kjører verdikjedetestene for verdikjeden

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'CODEOWNERS'
      - '.github/workflows/build-pr.yml'
      - '.github/workflows/fpsak-trigger.yml'
      - '.github/workflows/fptilbake-trigger.yml'
      - '.github/workflows/notify-slack.yml'
      - '.github/workflows/update-issue.yml'
      - 'lokalutvikling/*'
      - 'docs/*'
  repository_dispatch:
    types: [fpsak-verdikjede, fpabakus-verdikjede, fpformidling-verdikjede, fpabakus-verdikjede, fpoppdrag-verdikjede, fprisk-verdikjede, fpabonnent-verdikjede, fordel-verdikjede, info-verdikjede, mottak-verdikjede]
  schedule:
    - cron:  '30 5 * * *'

jobs:
  build:
    name: Utfør verdikjede-test for ${{ github.event.client_payload.trigger }} ${{ github.event.client_payload.version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set cache key
        run: |
          echo "CACHE_KEY=$(expr $(date +%V) - 1 + 1)" >> $GITHUB_ENV
          echo "PREVIOUS_CACHE_KEY=$(expr $(date +%V) - 1)" >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ env.PREVIOUS_CACHE_KEY }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.15

      - name: Setup verdikjeden
        shell: bash
        run: |
          echo "STACK_STARTED=false" >> $GITHUB_ENV
          echo "Oppretter dummy keystore for testing"
          cd resources/keystore
          ./make-dummy-keystore.sh
          echo "${{ secrets.GH_ACCESS_TOKEN }}" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          echo "${{ secrets.GH_ACCESS_TOKEN }}" | docker login --username "x-access-token" --password-stdin ghcr.io
          cd ../pipeline
          ./update-versions.sh ${{ github.event.client_payload.trigger }} ${{ github.event.client_payload.version }}
          docker-compose up --quiet-pull --detach fpsak fpformidling fpdokgen fpoppdrag fptilbake fprisk fpabonnent fpinfo fpfordel fpsoknad-mottak

      - name: Venter på stacken og sjekker status
        shell: bash
        run: |
          echo "STACK_CREATED=true" >> $GITHUB_ENV
          docker ps -a
          echo
          echo "Tester om VTP er oppe"
          timeout 5 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8060/rest/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo
          echo "Tester om fpabakus er oppe"
          timeout 180 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8015/fpabakus/internal/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo
          echo "Tester om fpsak er oppe"
          timeout 120 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/fpsak/internal/health/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo
          echo "Tester om fpformidling er oppe"
          timeout 60 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8010/fpformidling/internal/health/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo
          echo "Tester om fpdokgen er oppe"
          timeout 60 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8291)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo
          echo "Tester om fpoppdrag er oppe"
          timeout 60 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8070/fpoppdrag/internal/health/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo
          echo "Tester om fptilbake er oppe"
          timeout 60 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8030/fptilbake/internal/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo
          echo "Tester om fprisk er oppe"
          timeout 60 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8075/fprisk/internal/health/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo
          echo "Tester om fpabonnent er oppe"
          timeout 60 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8065/fpabonnent/internal/health/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo
          echo "Tester om fpfordel er oppe"
          timeout 60 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8090/fpfordel/internal/health/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!
          echo
          echo "Tester om fpinfo er oppe"
          timeout 60 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8040/fpinfo/internal/health/isReady)" != "200" ]]; do sleep 2; done' || false
          echo Oppe!

          echo "STACK_STARTED=true" >> $GITHUB_ENV

      - name: Sjekker minneforbruk
        if: always()
        shell: bash
        run: |
          docker stats --no-stream
          free -m

      - name: Utfører verdikjedetestene
        if: always() && env.STACK_STARTED == 'true'
        id: tester
        shell: bash
        run: |
          mvn test --batch-mode --settings .github/.m2/settings.xml -P verdikjede > >(tee test-result-log.txt)
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Sjekker minneforbruk
        if: always()
        shell: bash
        run: |
          docker stats --no-stream
          free -m

      - name: Henter testresultat og setter outcome
        if: |
          always() &&
          env.STACK_STARTED == 'true' &&
          steps.tester.outcome != 'cancelled'
        shell: bash
        run: |
          echo "TEST_RESULTAT=$(grep -o 'Tests run: [0-9]\+, Failures: [0-9]\+, Errors: [0-9]\+, Skipped: [0-9]\+$' test-result-log.txt)" >> $GITHUB_ENV
          rm test-result-log.txt
          if [ ${{ steps.tester.outcome }} == success ]; then
            echo "Test success!"
            echo "TEST_OUTCOME=success" >> $GITHUB_ENV
          else
            echo "Test failure!"
            echo "TEST_OUTCOME=failure" >> $GITHUB_ENV
          fi

      - name: Oppdaterer issue med testresultat
        if: |
          always() &&
          steps.tester.outcome != 'skipped' &&
          steps.tester.outcome != 'cancelled' &&
          github.event_name == 'repository_dispatch' &&
          github.event.client_payload.issue-number != null &&
          github.event.client_payload.trigger != 'navikt/fp-abakus' &&
          github.event.client_payload.trigger != 'navikt/fp-sak'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          event-type: update-issue
          client-payload: |
            {
            "trigger": "${{ github.event.client_payload.trigger }}",
            "issue-number": "${{ github.event.client_payload.issue-number }}",
            "success": "${{ env.TEST_OUTCOME }}",
            "run_id": "${{ github.run_id }}"
            }

      - name: Notify slack
        if: |
          always() &&
          steps.tester.outcome != 'cancelled' &&
          github.event_name == 'repository_dispatch' &&
          github.event.client_payload.trigger != null &&
          github.event.client_payload.version != null
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          event-type: notify-slack
          client-payload: |
            {
            "trigger": "${{ github.event.client_payload.trigger }}",
            "version": "${{ github.event.client_payload.version }}",
            "stack_started": "${{ env.STACK_STARTED }}",
            "test_outcome": "${{ env.TEST_OUTCOME }}",
            "test_resultat": "${{ env.TEST_RESULTAT }}",
            "test_suite": "verdikjede",
            "run_id": "${{ github.run_id }}"
            }

      - name: Generer testrapport
        if: |
          always() &&
          env.STACK_STARTED == 'true' &&
          steps.tester.outcome != 'cancelled' &&
          github.event_name == 'repository_dispatch'
        id: ghpages
        shell: bash
        run: |
          git fetch origin gh-pages
          mkdir gh-pages
          git --work-tree=gh-pages checkout origin/gh-pages -- fpsak
          git --work-tree=gh-pages checkout origin/gh-pages -- verdikjede/history
          resources/allure/set-environment-variables.sh ${{ github.event.client_payload.trigger }}
          cp resources/allure/environment.properties target/allure-results
          cp resources/allure/categories.json target/allure-results
          cp -r gh-pages/verdikjede/history target/allure-results
          mvn allure:report --batch-mode --file pom.xml
          cp -a target/allure-report/. gh-pages/verdikjede/

      - name: Deploy testrapport
        if: always() && steps.ghpages.outcome == 'success'
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          build_dir: gh-pages
        env:
          GH_PAT: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Dumper logger for feilsøking
        if: failure() && env.STACK_CREATED == 'true'
        run: |
          mkdir container-logs
          cd container-logs
          docker ps -a --format '{{.Names}}' | while read pod; do docker logs $pod > $pod.log 2>&1; done

      - name: Laste opp logger
        if: failure() && env.STACK_CREATED == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: container-logs

      - name: Sjekker minneforbruk og storage
        if: failure()
        shell: bash
        run: |
          docker stats --no-stream
          docker system df -v
          df -h
          free -m
